# Generated by Django 5.2.1 on 2026-04-23 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('flat', 'Flat'), ('house', 'House'), ('studio', 'Studio'), ('penthouse', 'Penthouse'), ('duplex', 'Duplex'), ('land', 'Land'), ('other', 'Other')], max_length=20)),
                ('operation_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=10)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('size_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('energy_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateAgency.location')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateAgency.source')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('model_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estateAgency.location')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estateAgency.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_elevator', models.BooleanField(blank=True, null=True)),
                ('has_garage', models.BooleanField(blank=True, null=True)),
                ('has_terrace', models.BooleanField(blank=True, null=True)),
                ('has_pool', models.BooleanField(blank=True, null=True)),
                ('condition_status', models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good'), ('renovation', 'Renovation'), ('needs_renovation', 'Needs Renovation')], max_length=20, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='estateAgency.property')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estateAgency.source')),
            ],
        ),
        migrations.CreateModel(
            name='AreaStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_price_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_properties', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='estateAgency.location')),
            ],
            options={
                'unique_together': {('location', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='estateAgency.property')),
            ],
            options={
                'indexes': [models.Index(fields=['price'], name='estateAgenc_price_8c466c_idx'), models.Index(fields=['scraped_at'], name='estateAgenc_scraped_f0fbe2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='estateAgenc_propert_7ffaf2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['operation_type'], name='estateAgenc_operati_f4c988_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('external_id', 'source')},
        ),
    ]
