# Generated by Django 5.2.1 on 2026-04-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rental_type',
            field=models.CharField(blank=True, choices=[('short', 'Short Term'), ('long', 'Long Term')], max_length=10, null=True),
        ),
    ]
