# Generated by Django 5.2.1 on 2026-04-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0003_areastats_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
