# Generated by Django 5.2.1 on 2026-04-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateAgency', '0004_property_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyFeature',
        ),
    ]
